### ISSUE TITLE
nkn-wallet SDK should appointed dependent module version

### ISSUE THREAD

**Issue by gdmmx** [nknorg/nkn-wallet-js#14]
Since base-x@**3.0.5** [base-x commit 172a3d2](https://github.com/cryptocoinjs/base-x/pull/49/files/172a3d2bac0ef0a0b41962a8271ef88cfc804c46?utf8=✓&diff=unified#diff-168726dbe96b3ce427e7fedce31bb0bc), base module required argument of encode() **MUST** isBuffer.

```
# node --version
v9.11.2
# npm -v
6.4.1
# npm list base-x
/usr/lib
└── base-x@3.0.5
# cd nkn-wallet-js && git log |head -1
commit f14a3f1feda039b1a2739f1e7470ddebac46a527

# node examples/node_example.js
/usr/lib/node_modules/base-x/index.js:29
    if (!Buffer.isBuffer(source)) throw new TypeError('Expected Buffer')
                                  ^
TypeError: Expected Buffer
    at Object.encode (/usr/lib/node_modules/base-x/index.js:29:41)
    at Object.programHashString2Address (/home/admin/nkn-wallet-js/lib/crypto/algorithm.js:163:17)
    at new account (/home/admin/nkn-wallet-js/lib/crypto/account.js:29:27)
    at Object.newAccount (/home/admin/nkn-wallet-js/lib/crypto/account.js:61:10)
    at Object.newWallet (/home/admin/nkn-wallet-js/lib/wallet.js:317:28)
    at Object.<anonymous> (/home/admin/nkn-wallet-js/examples/node_example.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```

**Comment by AKACoder** [comment]
use fixed base-x version@3.0.4
